# Generated by Django 2.2.17 on 2020-11-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="hello",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
